# SBC_pollution_China Data Studio

This notebook has been generated on 2020-03-01 10:37 

## Instruction to create connection

1. Sign in

To load the Data from Google, you need log in  with your Google Account. You need to run the cell with the function `connector.get_token()`. 

During this step, you'll be prompt to accept the app to read data in Google Doc, Spreadsheet and Drive. The app **will not** read data in your account since the data are uploaded from the owner of the dataset. 

For safety reason, Google warns you that the app isn't verify. We haven't verify the app since it is a private use only. Click on **Advanced** and then **connect to connect_py**

![](https://github.com/thomaspernet/DataLab-JupyterNotebooks/blob/master/Instruction_workflow/verify_app_1.png?raw=true)

It will download a token in the virtual machine. Since the machine is destroy when the jupyter  notebook is closed, **the credentials will not be saved**

Note, if you use the studio locally, and you have already a token, you can use you your personal token. In this case, you don't need to run the cell `connector.get_token()`. However, you need to change the cell 

```
gs = connector.open_connection(online_connection = True)
```

to 

```
gs = connector.open_connection(online_connection = False, path_credential = '/PATH_CREDENTIAL/')
```

In [ ]:
import pandas as pd
from Fast_connectCloud import connector

### Sign in to console

Run the cell below to log in to the console. If you run the notebook locally, skip the next cell and change `connector.open_connection(public_connection=None)` to `connector.open_connection(online_connection = False, path_credential = '/PATH_CREDENTIAL/')`

In [ ]:
connector.get_token()

### Open the connection

The cell below create the connection with Google Cloud.

In [ ]:
gs = connector.open_connection(online_connection = True)

service = gs.connect_remote('GCP')

# Load the data

Data is located in Google Sheet:

- [SBC_pollution_China](HERE)

The variables names and labels are the following:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Variables</th>
      <th>Labels</th>
      <th>Types</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>year</td>
      <td>year</td>
      <td>int64</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Period</td>
      <td>Period</td>
      <td>object</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Province_en</td>
      <td>Province_en</td>
      <td>object</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Lower_location</td>
      <td>Lower_location</td>
      <td>object</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Larger_location</td>
      <td>Larger_location</td>
      <td>object</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Coastal</td>
      <td>Coastal</td>
      <td>bool</td>
    </tr>
    <tr>
      <th>6</th>
      <td>cityen</td>
      <td>cityen</td>
      <td>object</td>
    </tr>
    <tr>
      <th>7</th>
      <td>geocode4_corr</td>
      <td>geocode4_corr</td>
      <td>int64</td>
    </tr>
    <tr>
      <th>8</th>
      <td>TCZ_c</td>
      <td>TCZ_c</td>
      <td>object</td>
    </tr>
    <tr>
      <th>9</th>
      <td>target_c</td>
      <td>target_c</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>10</th>
      <td>effort_c</td>
      <td>effort_c</td>
      <td>object</td>
    </tr>
    <tr>
      <th>11</th>
      <td>industry</td>
      <td>industry</td>
      <td>int64</td>
    </tr>
    <tr>
      <th>12</th>
      <td>ind2</td>
      <td>ind2</td>
      <td>int64</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Short</td>
      <td>Short</td>
      <td>object</td>
    </tr>
    <tr>
      <th>14</th>
      <td>output_fcit</td>
      <td>output_fcit</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>15</th>
      <td>capital_fcit</td>
      <td>capital_fcit</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>16</th>
      <td>labour_fcit</td>
      <td>labour_fcit</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>17</th>
      <td>count_SOE</td>
      <td>count_SOE</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>18</th>
      <td>out_share_SOE</td>
      <td>out_share_SOE</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>19</th>
      <td>cap_share_SOE</td>
      <td>cap_share_SOE</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>20</th>
      <td>lab_share_SOE</td>
      <td>lab_share_SOE</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>21</th>
      <td>tso2_cit</td>
      <td>tso2_cit</td>
      <td>int64</td>
    </tr>
    <tr>
      <th>22</th>
      <td>tso2_i</td>
      <td>tso2_i</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>23</th>
      <td>tCOD_cit</td>
      <td>tCOD_cit</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>24</th>
      <td>twaste_water_cit</td>
      <td>twaste_water_cit</td>
      <td>int64</td>
    </tr>
    <tr>
      <th>25</th>
      <td>polluted_di</td>
      <td>polluted_di</td>
      <td>object</td>
    </tr>
    <tr>
      <th>26</th>
      <td>polluted_mi</td>
      <td>polluted_mi</td>
      <td>object</td>
    </tr>
    <tr>
      <th>27</th>
      <td>polluted_thre</td>
      <td>polluted_thre</td>
      <td>object</td>
    </tr>
    <tr>
      <th>28</th>
      <td>FE_c_i</td>
      <td>FE_c_i</td>
      <td>int64</td>
    </tr>
    <tr>
      <th>29</th>
      <td>FE_t_i</td>
      <td>FE_t_i</td>
      <td>int64</td>
    </tr>
    <tr>
      <th>30</th>
      <td>FE_t_c</td>
      <td>FE_t_c</td>
      <td>int64</td>
    </tr>
    <tr>
      <th>31</th>
      <td>out_share_for</td>
      <td>out_share_for</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>32</th>
      <td>out_share_soe1</td>
      <td>out_share_soe1</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>33</th>
      <td>cap_share_for</td>
      <td>cap_share_for</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>34</th>
      <td>cap_share_soe1</td>
      <td>cap_share_soe1</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>35</th>
      <td>lab_share_for</td>
      <td>lab_share_for</td>
      <td>float64</td>
    </tr>
    <tr>
      <th>36</th>
      <td>lab_share_soe1</td>
      <td>lab_share_soe1</td>
      <td>float64</td>
    </tr>
  </tbody>
</table>

## Load the data

In [ ]:

from GoogleDrivePy.google_platform import connect_cloud_platform
project = 'v'
gcp = connect_cloud_platform.connect_console(project = project, 
                                             service_account = service['GoogleCloudP'])    
query = (
          "SELECT * "
            "FROM China.SBC_pollution_China "

        )

df_final = gcp.upload_data_from_bigquery(query = query, location = 'US')
df_final.head()

## Load DataViz Studio

- Remember to select:
    - Cells -> Current output -> Toggle

We set cdr to cdr since we want to save the report in the drive

In [ ]:
from DataAnalysisPy.AnalysisPy import QuickDescriptive
%matplotlib inline

You can filter the cell below and re-launch the studio to get the filtered dataframe

In [ ]:
### Load interactive frame
qgrid_widget = QuickDescriptive.grid_search(df = df_final,
                             rows_to_display = 10)
qgrid_widget

In [ ]:
#### temporary method
new_df = qgrid_widget.get_changed_df()
QuickDescriptive.PyAnalysis(dataframe=new_df,
                           automatic = True,
                           Date = ''year'',
                            cdr = False)